version: "3.8"
services:
  sqlalchemy:
    build: 
      context: . 
    image: dev
    stdin_open: true
    tty: true

  psql:
    image: postgres:16.1-alpine3.19
    environment:
      - POSTGRES_DB=mydb
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=fish123
    volumes: 
      - db-data:/var/lib/postgresql/data



volumes:
  db-data: 
    name: db-data
